# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Cytomining hackathon"
email: "imagingadmin@broadinstitute.org"
description: "Cytomining Hackathon"
baseurl: ""
url: "https://hack.cytominr.org"
#permalink: "/blog/:title"

# Organizer Info
organizerName: "Broad Institute | Imaging Platform"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.broadinstitute.org/~anne/"

# Head
metaKeywords: "profiling, imaging"
twitterAccount: "@cellprofiler"
addThisEvent: true
socialImageSrcGooglePlus: "/img/sections-background/hero.jpg"
socialImageSrcTwitter: "/img/sections-background/hero.jpg"
socialImageSrcFacebook: "/img/sections-background/hero.jpg"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "#schedule", text: "Schedule"}
 - {permalink: "#direction-details", text: "Logistics"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "#team", text: "Organizers"}
bottomNavigationLinks:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "schedule.jpg"
heroTitle: "<typeout> Hackathon"
eventDate: "<h4>Boston, MA<br>TBA 2016</h4>"
typeoutTextValues: '"Morphological profiling", "Cytomining"'
typeoutFallback: "Cytomining "
heroButtons:
 #- {link: "https://github.com/broadinstitute/cytomining-hackathon/wiki", text: "Join the public conversation on GitHub"}
 #- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Cytomining in Action"
aboutBlock:
 - {title: "Make history", image: "conference.jpg", text: "The first ever Cytomining Hackathon. Attend, ask questions and have fun." }
 - {title: "Initiate collaboration", image: "workshop.jpg", text: "Identify novel methods, standards, and a basis for best practices" }
 - {title: "Build the community", image: "hackathon.jpg", text: "Morphological profiling experts will join together for seminars, lectures, social events, and hacking" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "attendees", detail: "from rockstar labs"}
 - {count: "5", specialCharacter: "+", info: "tables", detail: "of snacks, pizza and beer"}
 - {count: "2", specialCharacter: "", info: "awesome days", detail: "for hacking, community-building and fun"}

# Latest News Block (We dont need )
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Hampton Inn and Suites Boston Crosstown Center"
eventLocationLink: "http://bostonhamptoninn.com/"
eventStreetAddress: "811 Massachusetts Avenue"
eventAddressLocality: "Boston"
eventAddressLocalityRegion: "MA"
eventPostalCode: "02118"
eventAddressCountry: "USA"
eventStartTime: ""
eventDoorTime: ""
eventEndTime: ""
eventPlaceCoordinates: "42.3325759,-71.0729888"
mapCenterCoordinates: "42.3325759,-71.0729888"
mapMobileCenterCoordinates: "42.3325759,-71.0729888"

# Venue Block
venueBlockTitle: "Hampton Inn and Suites Boston Crosstown Center"
venueBigImage: "venue__1.jpg"
venueSmallImage1: "venue__2.jpg"
venueSmallImage2: "venue__3.jpg"
venueSmallImage3: "venue__3.jpg"
venueTitle: "Located at 811 Massachusetts Ave, Boston, MA 02118"
venueFeatures:

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Catch up and check in"
twitterHashTag: "cytomining"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Funding"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block (we dont need)
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

#Tickets Block (We dont need)
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
-
 name: "Early Bird"
 price: "350"
 priceCurrency: "UAH"
 ticketsNumber: "150"
 ribbon: "-5%"
 buyButtonLink: "http://dfua.ticketforevent.com/"
 buyButtonText: "Buy Now"
 ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 validFrom: "2014-08-25T10:00"
 validThrough: "2014-09-30T23:59"
-
 name: "Last Chance"
 price: "450"
 priceCurrency: "UAH"
 ticketsNumber: "100"
 ribbon: "-20%"
 featured: true
 buyButtonLink: "http://dfua.ticketforevent.com/"
 buyButtonText: "Buy Now"
 ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 validFrom: "2014-10-01T00:00"
 validThrough: "2014-10-23T23:59"
 disabled: true
-
 name: "Student"
 price: "200"
 priceCurrency: "UAH"
 ticketsNumber: "50"
 buyButtonLink: "http://dfua.ticketforevent.com/"
 buyButtonText: "Buy Now"
 additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
 ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 validFrom: "2014-08-20T10:00"
 validThrough: "2014-10-23T23:59"
 soldOut: true
 soldOutText: "Sold Out"

# Footer
#socialLinks:
 #- {link: "", icon: "google-plus"}
 #- {link: "", icon: "twitter"}
footerBlocks:
 -
  title: ""
  links:

 -
  title: "Contacts"
  links:
    - {link: "mailto:imagingadmin@broadinstitute.org", text: "imagingadmin@broadinstitute.org"}

 # -
 #  title: "FAQ"
 #  links:
 #   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Organizers"
aboutUs: "The Carpenter lab at the Broad Institute is organizing the event. The Carpenter Lab is based at the Broad Institute of MIT and Harvard in Cambridge, Massachusetts, USA. Our research group develops advanced methods and software tools to quantify and mine the rich information present in cellular images to yield biological discoveries. Our laboratory is best known for our open source software packages CellProfiler and CellProfiler Analyst, but our main focus these days is profiling: we are using advanced machine learning methods to identify morphological patterns in cell populations, to probe the causes and cures for disease."
# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "48.1506177,11.5470593"
logisticsMapMobileCenterCoordinates: "48.1506177,11.5470593"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "hero.jpg"
directionDetailsTitle: "Logistics"
directionDetailsCards:
 - {title: "Funding", information: 'Meeting room and group meals will be covered by the organizers/funders. Each participant should plan to finance their own travel and lodging (exception: some support can be provided for attendees from under-represented groups; please <a href="mailto:imagingadmin@broadinstitute.org?Subject=Hackathon%20Inquiry">contact us</a>). Please note that space is limited in order to maintain high levels of engagement.'}
 - {title: "Lodging", information: 'All sessions and lodging at the <a href="http://bostonhamptoninn.com/"><b>Hampton Inn and Suites</a> Boston Crosstown Center</b> located at <a href="http://bit.ly/1ZpYNOj">811 Massachusetts Ave</a>, Boston, MA 02118.  Room sharing with other participants will be facilitated for those who request it. If you choose to drive, the hotel offers a parking lot for $25.00/day'}
 - {title: "Transportation", information: 'The closest airport is <a href="https://www.massport.com/logan-airport/">Boston Logan Airport</a> (BOS). The hackathon hotel offers a free shuttle from BOS to the hotel. Other airports are Manchester, NH (MHT, 1 hr drive) and Providence (PVD, 1 hr drive). <br> <br>The Boston MBTA <a href="http://www.mbta.com/uploadedFiles/Documents/Schedules_and_Maps/Bus/routesilverwater(5).pdf">Silver line</a> can also bring you from the airport to the hotel. Take the Silver line bus 1 (SL1) which you can find outside Terminals A-E (stops every 8-15 minutes from 5:30 am to 2:00 am).Take it to South Station to transfer to the Silver line bus 4 (SL4). Take the SL4 to Washington St @ Massachusetts Ave and walk northeast on Washington St toward Massachusetts Ave until you reach 811 Massachusetts Ave. '}
directionDetailsWideCards:
 -
  #title: "Questions?"
  #subCards:
   #-
    #title: "Hotels"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
    #title: "Registration"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
    #title: "Attendance Details"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Why should you attend?"
hackathonRows:
 - {title: "", image: "unnamed.gif", details: "Researchers mining image data are gaining momentum: papers are shifting from proof-of-principle to biological discovery. But we are not yet much of a true community, beyond reading each others’ papers and a few pairwise interactions at conferences. We would like to change this by bringing everyone together in the same room! Collectively, we have tremendous knowledge and insights into this challenging field."}
 - {title: "", image: "hackathon-1.png", details: "Twenty participants from the front lines of analyzing morphological data will be invited to this first-ever hackathon, including postdocs, students, and staff scientists. In weeks leading up to the event, participants will join in a <a href='https://github.com/broadinstitute/cytomining-hackathon/wiki'>public discussion on Github</a>, mapping out options for analysis at various steps in the workflow. Attendees will then join together for seminars, lectures, social events, and hacking during a two-day event in Boston. We aspire to gather a diverse and engaged group of both morphological profiling experts and members of related fields, such as alternate profiling methodologies. Everyone involved will be an active contributor (even if remote), no passive absorption of others’ ideas allowed!"}
links:
 - {link: "mailto:imagingadmin@broadinstitute.org", text: "Imaging Platform | Broad Institute"}

# Hackathon Judges Block (We dont need)
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block (We dont need)
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block (We dont need)
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Fakultät für Informatik"
hackathonLocationLink: "http://tum.de/"
hackathonStreetAddress: "Boltzmannstraße 3"
hackathonAddressLocality: "Munich"
hackathonAddressLocalityRegion: "Bavaria"
hackathonPostalCode: "85748"
hackathonAddressCountry: "Germany"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 11.669776"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
